spring.application.name=buvette-backend
spring.data.mongodb.uri=mongodb://localhost:27017/buvette
spring.data.mongodb.database=buvette
server.port=8088
logging.level.org.springframework.security=DEBUG
logging.level.com.buvette.buvette_backend=DEBUG

